---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

<div class="alert alert-dismissible alert-info">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>New label!</strong> The 'new' label denotes the most recently delivered report(s).
</div>


This  website contains scRNA-seq data analyses and integration with targeted mutation for scmseq project.

# AML patients from Chiara

- [1-Exploratory analysis and malignant cell annotation](00_malignant_non_malignant_annotations.html)
- [2-Tumor microenviroment identification](01_tme_annotation.html)
- [3-Phenotype genotype integration in sAML1](02_integration_phenotype_genotype_sAML1.html)
- [4-Phenotype genotype integration in AML4](03_integration_phenotype_genotype_AML4.html)
- [5-Phenotype genotype integration in AML5](04_integration_phenotype_genotype_AML5.html)

# PALM patients

- [1-Exploratory analysis and malignant cell annotation](00_palm_malignant_non_malignant_annotations.html)
- [2-Tumor microenviroment identification](01_palm_tme_annotation.html)
- [3-Phenotype genotype integration in PALM04](02_integration_phenotype_genotype_PALM04.html)
- [4-Phenotype genotype integration in PALM06](05_integration_phenotype_genotype_PALM06.html) 
- [5-Phenotype genotype PALM08R nested PCR](07_nested_pcr_palm08_genotype.html) 
- [6-Phenotype genotype PALM08R nested PCR no bio](08_nested_pcr_palm08_nobio_genotype.html)
- [7-Phenotype genotype PALM08R nested PCR no bax](09_nested_pcr_palm08_nobax_genotype.html)
- [8-Phenotype genotype PALM08R nested PCR bio pooled (5-7 pooled)](10_nested_pcr_palm08_bio_pooled_genotype.html) 
- [9-Phenotype genotype PALM08E nested PCR](11_nested_pcr_PALM08_E.html) 
- [10-Phenotype genotype PALM07E nested PCR](12_nested_pcr_PALM07_E.html)
- [11-Phenotype genotype PALM14E nested PCR](13_PALM14_E.html) 
- [12-Phenotype genotype PALM14R nested PCR](14_PALM14_R.html) 
- [13-PALM08E SNP](15_PALM08_E_SNP.html) 
- [14-PALM08R SNP](16_PALM08_R_SNP.html)
- [15-Phenotype genotype PALM11E nested PCR](17_PALM11_E.html)
- [16-Phenotype genotype PALM11E pooled](18_PALM11_E_pooled.html) <span class="label btn-warning"> New report</span>
- [17-Phenotype genotype PALM09E pooled](19_PALM09_E_pooled.html) <span class="label btn-warning"> New report</span>



# Malignant cell annotation
- [1-malignant cell annotation using expansion and SCEVAN](00a_benchmark_malignant_cell.html) <span class="label btn-warning"> New report</span>